export const depts: any = [
  { graduation: 'pg', value: 'mca', dept: 'Master of Computer Application' },
  {
    graduation: 'pg',
    value: 'msc_cs_sf',
    dept: 'Master of Computer Science SF',
  },
  { graduation: 'pg', value: 'msc_cs_r', dept: 'Master of Computer Science R' },
  { graduation: 'pg', value: 'msc_maths', dept: 'Master of Mathematics' },
  { graduation: 'pg', value: 'ma_tamil', dept: 'Master of Tamil' },
  { graduation: 'pg', value: 'ma_english', dept: 'Master of English' },
  { graduation: 'pg', value: 'ma_history', dept: 'Master of History' },
  { graduation: 'pg', value: 'mcom_r', dept: 'Master of Commerce R' },
  { graduation: 'ug', value: 'bca', dept: 'Bachelor of Computer Application' },
  {
    graduation: 'ug',
    value: 'bsc_cs_r',
    dept: 'Bachelor of Computer Science R',
  },
  {
    graduation: 'ug',
    value: 'bsc_cs_sf',
    dept: 'Bachelor of Computer Science SF',
  },
  { graduation: 'ug', value: 'bsc_maths', dept: 'Bachelor of Mathematics' },
  { graduation: 'ug', value: 'ba_tamil', dept: 'Bachelor of Tamil' },
  { graduation: 'ug', value: 'ba_english', dept: 'Bachelor of English' },
  { graduation: 'ug', value: 'ba_history', dept: 'Bachelor of History' },
  { graduation: 'ug', value: 'bcom_ca', dept: 'Bachelor of Commerce CA' },
  { graduation: 'ug', value: 'bcom_r', dept: 'Bachelor of Commerce R' },
  { graduation: 'ug', value: 'bcom_sf', dept: 'Bachelor of Commece SF' },
];
